//go:generate go install -v github.com/josephspurrier/goversioninfo/cmd/goversioninfo
package main

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/portapps/portapps/v3"
	"github.com/portapps/portapps/v3/pkg/files"
	"github.com/portapps/portapps/v3/pkg/log"
)

var (
	app *portapps.App
)

const (
	vmOptionsFile = "studio.vmoptions"
)

func init() {
	var err error

	// Init app
	if app, err = portapps.New("android-studio-portable", "Android Studio"); err != nil {
		log.Fatal().Err(err).Msg("Cannot initialize application. See log file for more info.")
	}
}

func main() {
	if err := os.MkdirAll(app.DataPath, 0o755); err != nil {
		log.Fatal().Err(err).Msg("Cannot create data path")
	}
	app.Process = filepath.Join(app.AppPath, "bin", "studio64.exe")
	app.WorkingDir = filepath.Join(app.AppPath, "bin")

	// override idea.properties
	studioPropContent := strings.ReplaceAll(`# DO NOT EDIT! AUTOMATICALLY GENERATED BY PORTAPPS.
idea.config.path={{ DATA_PATH }}/config
idea.system.path={{ DATA_PATH }}/system
idea.plugins.path={{ DATA_PATH }}/plugins
idea.log.path={{ DATA_PATH }}/log`, "{{ DATA_PATH }}", strings.ReplaceAll(app.DataPath, `\`, `/`))

	studioPropPath := filepath.Join(app.DataPath, "idea.properties")
	if err := os.WriteFile(studioPropPath, []byte(studioPropContent), 0o644); err != nil {
		log.Fatal().Err(err).Msg("Cannot write idea.properties")
	}

	// https://developer.android.com/studio/command-line/variables
	os.Setenv("ANDROID_HOME", filepath.Join(app.DataPath, "sdk"))
	os.Setenv("ANDROID_SDK_ROOT", filepath.Join(app.DataPath, "sdk"))
	os.Setenv("ANDROID_SDK_HOME", filepath.Join(app.DataPath, ".android"))
	os.Setenv("GRADLE_USER_HOME", filepath.Join(app.DataPath, ".gradle"))

	// https://developer.android.com/studio/intro/studio-config
	os.Setenv("STUDIO_PROPERTIES", studioPropPath)
	os.Setenv("STUDIO_VM_OPTIONS", filepath.Join(app.DataPath, vmOptionsFile))
	if !files.Exists(filepath.Join(app.DataPath, vmOptionsFile)) {
		files.CopyFile(filepath.Join(app.AppPath, "bin", "studio64.exe.vmoptions"), filepath.Join(app.DataPath, vmOptionsFile))
	} else {
		files.CopyFile(filepath.Join(app.DataPath, vmOptionsFile), filepath.Join(app.AppPath, "bin", "studio64.exe.vmoptions"))
	}

	defer app.Close()
	app.Launch(os.Args[1:])
}
